<!-- Open Graph Data -->
<meta property="og:site_name" content="{{ data.project.title }}" />
<meta property="og:title" content="{{ data.local.header.title }}" />
<meta property="og:description" content="{{ data.local.header.description }}" />
<meta property="og:type" content="The type of your object, e.g., 'video.movie'. Depending on the type you specify, other properties may also be required." />
<meta property="og:url" content=" The canonical URL of your object that will be used as its permanent ID in the graph, e.g., 'http://www.imdb.com/title/tt0117500/'" />
<meta property="og:image" content="{{ data.local.header.image }}" />
<!-- /Open Graph Data -->