<!--[if IE 9]>
<script src="/prototype/static/js/shim.js"></script>
<![endif]-->
<script src="/prototype/static/js/initial.js" data-inline></script>

<script>
    DEBUG = {
        A11Y: false, // load a11y helpers/warnings
        BASELINE: true, // show baseline toggle
        COUNT: false, // count CSS selectors/rules
        CSS: true // load debug CSS (baseline, ...)
    };
</script>
<script src="/prototype/static/js/debug.js"></script>